### ISSUE TITLE
не подгружаются стили

### ISSUE THREAD

**Issue by Amirrkhan** [agragregra/OptimizedHTML-4#10]
При открытии index.html без gulp просто двойным кликом -  не подгружаются стили. Мне нужно отправить сделанное задание на проверку. Как без билда сделать чтобы стили подгружались?

**Comment by alex-grsm** [comment]
убери эту строку 
 base href="/"

**Comment by Amirrkhan** [comment]
с этой строкой у меня были проблемы, когда я верстал внутренние страницы. Там по клику на любую ссылку во внутренней странице, всегда перекидывало на index.html. В общем спасибо, я ее не замечал(

**Comment by maxdzyubak** [comment]
Благодарю! Была та же проблема.
