### ISSUE TITLE
body height = 0

### ISSUE THREAD

**Issue by kalininss** [agragregra/OptimizedHTML-4#15]
При верстке возникает проблема, что высота body = 0, либо равна высоте viewport.

Причиной является строка №15 в файле:
app/scss/main.scss

html, body {
	height: 100%;
}

**Comment by alex-grsm** [comment]
у меня с этими стилями тоже были проблемы, еще в предыдущем шаблоне. Удалил и живу спокойно.
так и не понял зачем эти стили...

**Comment by banha-serhii** [comment]
@alex-grsm насколько помню, нужно для того, что бы прижимать футур к низу страницы при верстке на флексах
