### ISSUE TITLE
Файл _media.sass не генерирует медиа запросов

### ISSUE THREAD

**Issue by WhoIsDT** [agragregra/OptimizedHTML-4#17]
Обратите внимание на то, что в файле _media.sass содержатся ошибки, согласно новых стандартов сетки. У вас значение md  должно быть за менено на lg (в комментариях) и добавить новый диапазон xl

**Comment by wdmcourses** [comment]
Уверяю вас, всё проверено и оттестировано на реальных проектах. Всё работает как часы.
Медиазапросы идентифицированы верно. XL работает только в Mobile First секции. Чтобы понять, почему - почитайте документацию.
