### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by kierok** [agragregra/OptimizedHTML-4#2]
Hello. Why there is no build task in this version of starter, like it was in prev version?

**Comment by SeRGei93** [comment]
Привет. а как собрать ?

**Comment by kierok** [comment]
Привет.


gulp.task('imagemin', function() {
return gulp.src('app/img/**/*')
.pipe(gulp.dest('dist/img'));
});


gulp.task('build', ['removedist', 'imagemin', 'sass', 'js'], function() {

var buildFiles = gulp.src([
'app/*.html',
'app/.htaccess',
]).pipe(gulp.dest('dist'));

var buildCss = gulp.src([
'app/css/main.min.css',
]).pipe(gulp.dest('dist/css'));

var buildJs = gulp.src([
'app/js/scripts.min.js',
]).pipe(gulp.dest('dist/js'));

var buildFonts = gulp.src([
'app/fonts/**/*',
]).pipe(gulp.dest('dist/fonts'));

});


gulp.task('removedist', function() { return del.sync('dist'); });

плюс поставить gulp-imagemin и del.

это калька точная с прошлого стартового шаблона.

кастомные решения могу потом помочь написать.
но я с postcss больше работаю, так что галп будем совсем другим и с другими
npm)

2018-02-11 13:06 GMT+02:00 Sergei Stefanovich <notifications@github.com>:

**Comment by SeRGei93** [comment]
Привет. Уже разобрался сам. Спасибо)

11 февраля 2018 г., 14:24 пользователь kierok <notifications@github.com>
написал:
