### ISSUE TITLE
Установка модулей

### ISSUE THREAD

**Issue by mrgyf1** [agragregra/OptimizedHTML-4#21]
После установки всех модулей с помощью "npm install", при попытке запустить gulp появляется ошибка с просьбой установить сначала gulp-util, далее установить gulp-sass и все зависимости вручную.. Чем может быть вызвано такое поведение?

**Comment by mrgyf1** [comment]
Самое интересное, что если использовать подсистему Linux, то такие ошибки, а если GIT Bash, то все ок

**Comment by ghost** [comment]
Нужно работать в каком-то одном терминале. Если прыгать из одного (Linux) в другую(Git), то придется всегда ребилд делать (Вроде команда npm rebuild node sass -- force) Поправьте, если ошибаюсь. Замечено лично уже давно.

**Comment by ghost** [comment]
Я для себя выбрал так - работаю в Bash, а если до rsync дело доходит, то linux
