### ISSUE TITLE
Wordpress 

### ISSUE THREAD

**Issue by mrgyf1** [agragregra/OptimizedHTML-4#22]
Подскажите пожалуйста, как правильно использовать gulp (optimizedHTML4 + wordpress), какие настройки необходимо изменить, чтобы все работало не на костылях

**Comment by maxx52** [comment]
Посмотри [тут](https://gist.github.com/maxx52/696d9e0f51a5d57ffeb96de2db8ec41b), там для OpenCart, но все по образу и подобию, просто пути поменяй.
