### ISSUE TITLE
проблема с _media.sass

### ISSUE THREAD

**Issue by vitaliy-tkachuk** [agragregra/OptimizedHTML-4#23]
Если в _media.sass менять параметры которые уже были указаны для данного селектора в main.sass, то они игнорируются, помогает только указание для каждого параметра !important. Это баг или фича?

пример:

```
main.sass :

.selector
   left: 100px


_media.sass : 

+media-breakpoint-down(sm)
  .selector
    left: 20px
    color: red
```

В этом примере left: 20px будет проигнорирован, а color: red применится. Если указать left: 20px !important, только в этом случае он будет учтен.

В scss файлах все работает отлично и никаких проблем с _media.scss не было замечено.

**Comment by talifa** [comment]
У меня эта проблема решилась, когда в медиа запросах свойства прописывались с тем же наследованием, что и в основных файлах. Нпрмр:
Если в main у вас 
`.wrapper ul li .ant {..}`
то в медиа должна сохраниться цепочка, задавать свойство просто для `.ant {} `получится только с импотант.

**Comment by ABabiy** [comment]
> У меня эта проблема решилась, когда в медиа запросах свойства прописывались с тем же наследованием, что и в основных файлах. Нпрмр:
> Если в main у вас
> `.wrapper ul li .ant {..}`
> то в медиа должна сохраниться цепочка, задавать свойство просто для `.ant {}`получится только с импотант.

Верно. Цепочка должна быть идентичной или глубже
