### ISSUE TITLE
Может стоит добавить команду build?

### ISSUE THREAD

**Issue by lozovyk** [agragregra/OptimizedHTML-4#26]
Деплой сразу на сервер хорош, все же бывают ситуации когда он попросту не нужен, так как отдать нужно исключительно верстку.

Так же вопрос почему не используеться babel?
ES6 уже почти стандарт и сокращает время написания очень сильно.
В то же время IE 9/10+ так же являеться стандартом а там половина популярных плагинов по типу "glide.js" не работают.

**Comment by abraus** [comment]
> Деплой сразу на сервер хорош, все же бывают ситуации когда он попросту не нужен, так как отдать нужно исключительно верстку.

А в чём проблема деплоить верстку? У меня верстка (стили, скрипты, картинки и прочее) сразу деплоится в уже работающий сайт на MODX. Правда я в этот сборщик еще добавил оптимизацию картинок и сборку спрайта svg.

**Comment by lozovyk** [comment]
> А в чём проблема деплоить верстку? У меня верстка (стили, скрипты, картинки и прочее) сразу деплоится в уже работающий сайт на MODX. 

Ну бывает момент когда тебе не предоставляют доступ к хостингу, а человека который будет садить это все на бек нету в данный момент, или вовсе будут делать самопис.

**Comment by wdmcourses** [comment]
Билд - дело интимное. Каждому требуется свой результат.

**Comment by lozovyk** [comment]
> Билд - дело интимное.

Можно сделать один общий пресет и уже каждый сможет его подркутить под себя, тоже самое касаеться и babel как по мне.
Продуктом пользуються в основном начанающие разработчики из под Windows, у них возникнуть трудности при использовании команды **deploy**, так как во первых есть проблемы с подсистемой которая в течении 2019 возможно станет нормально работать :)
Во вторых возможно деплоить будет некуда так как это чисто их тестовые проекты.

**Comment by wdmcourses** [comment]
Думаю, функция билда будет неуместна.
