### ISSUE TITLE
Не запускается сборка проекта.

### ISSUE THREAD

**Issue by zinovyevaleks** [agragregra/OptimizedHTML-4#27]
При запуске Gulp выдаёт ошибку.

![image](https://user-images.githubusercontent.com/22955828/51010634-c3b99b00-1587-11e9-8050-52fe91e4d387.png)

 С тертьей версией работает нормально. Подскажите, куда копать?

**Comment by wdmcourses** [comment]
Обновите пакеты, Gulp локальный и глобальный.

**Comment by zinovyevaleks** [comment]
[13:05:24] CLI version 2.0.1
[13:05:24] Local version 4.0.0

Обновил. Запускается. Теперь стили не компилирует.

**Comment by abraus** [comment]
> [13:05:24] CLI version 2.0.1
> [13:05:24] Local version 4.0.0
> 
> Обновил. Запускается. Теперь стили не компилирует.

А в терминале на что ругается?

**Comment by zinovyevaleks** [comment]
> > [13:05:24] CLI version 2.0.1
> > [13:05:24] Local version 4.0.0
> > Обновил. Запускается. Теперь стили не компилирует.
> 
> А в терминале на что ругается?

Да ни на что не ругается. Просто запускает стартовую страницу без стилей.
![image](https://user-images.githubusercontent.com/22955828/51018358-e2308e00-15a9-11e9-86ed-3b20dfe72aaf.png)

![image](https://user-images.githubusercontent.com/22955828/51018363-e52b7e80-15a9-11e9-9da4-d1e205cab3af.png)

**Comment by rusicsemenov** [comment]
Так у Вас все работает, он сообщил ip и порты по которым работает сайт. Проверьте путь к css

**Comment by AndreyLevonyuk** [comment]
Сначала нужно сформировать минифицированный CSS а для этого нужно запустить таск style.
После чего запускаете gulp.

**Comment by zinovyevaleks** [comment]
> Сначала нужно сформировать минифицированный CSS а для этого нужно запустить таск style.
> После чего запускаете gulp.

Вот тут не понял. Таск есть в gulpfile, gulp при запуске должен собрать минифицированный файл стиля, он этого не делает. До обновления gulp до 4 версии всё работает.

**Comment by AndreyLevonyuk** [comment]
> > Сначала нужно сформировать минифицированный CSS а для этого нужно запустить таск style.
> > После чего запускаете gulp.
> 
> Вот тут не понял. Таск есть в gulpfile, gulp при запуске должен собрать минифицированный файл стиля, он этого не делает. До обновления gulp до 4 версии всё работает.

У меня так же было, при запуске gulp тоже запустился проект без стилей. Посмотрел в папке app и увидел что отсутствует файл main.min.css. Просто запустил gulp style, после чего сформировался файл стилей ну и далее просто gulp. Компиляция SASS после этого нормально проходит.

**Comment by abraus** [comment]
> Вот тут не понял. Таск есть в gulpfile, gulp при запуске должен собрать минифицированный файл стиля, он этого не делает. До обновления gulp до 4 версии всё работает.

> У меня так же было, при запуске gulp тоже запустился проект без стилей. Посмотрел в папке app и увидел что отсутствует файл main.min.css. Просто запустил gulp style, после чего сформировался файл стилей ну и далее просто gulp. Компиляция SASS после этого нормально проходит.

Обычно не нужно запускать таск стилей отдельно. Посмотрите внимательно в галп-файле, какой синтаксис используете и в каком стили пишете)

**Comment by AndreyLevonyuk** [comment]
Хотя по идее должно работать просто запустив Gulp, так как таск styles выполняется первым...

**Comment by abraus** [comment]
Таки да)

**Comment by abraus** [comment]
Скорее всего или ошибка в стилях (точка с запятой к примеру в scss не проставлена) или синтаксис неверный. Хотя, если ошибка в стилях, консоль ругнуться должна. Но вроде было такое на памяти, что консоль молчала, а стили не компилились

**Comment by AndreyLevonyuk** [comment]
> Таки да)

Вот я тоже так сначала думал) не знаю почему но при распаковке архива, запуске npm i, затем gulp - в самый первый раз запускается без стилей. То есть при первом запуске почему-то таск styles не выполняется. Хотя синтаксис проверял изначально (использую SASS). Кстати при запуске во второй и последующие разы, отрабатывает нормально, даже если специально удалить файл main.min.css

**Comment by losthuman** [comment]
> Хотя по идее должно работать просто запустив Gulp, так как таск styles выполняется первым...

После запуска  gulp выполняется watch, styles будет выполняться только если будут изменения в наблюдаемых файлах.

**Comment by abraus** [comment]
Да, кстати, сейчас вот специально скачал, проверил. При первом запуске style.min.css не компилится. Как только вносишь изменения в scss\sass сразу компилится))

**Comment by zinovyevaleks** [comment]
Ну вот и разобрались. Продолжаем работать, спасибо!

**Comment by wdmcourses** [comment]
Fixed. Thanks.

**Comment by Nekspsy** [comment]
Та же проблема и не получается решить, помогите, пожалуйста.
```
neks@DESKTOP-ERR8QEQ:/mnt/f/Work/GitHub/SM$ gulp
[17:34:00] Using gulpfile /mnt/f/Work/GitHub/nekspsy.github.io/portfolio/S&Mitler/gulpfile.js
/usr/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                   ^
TypeError: Cannot read property 'apply' of undefined
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

В проекте:
```
neks@DESKTOP-ERR8QEQ:/mnt/f/Work/GitHub/SM$ gulp -v
[17:34:41] CLI version 3.9.1
[17:34:41] Local version 4.0.0
```
Глобально:
```
C:\WINDOWS\system32>gulp -v
[17:37:04] CLI version 2.0.1
```

**Comment by Nekspsy** [comment]
Та же проблема и не получается решить, помогите, пожалуйста.
```
neks@DESKTOP-ERR8QEQ:/mnt/f/Work/GitHub/SM$ gulp
[17:34:00] Using gulpfile /mnt/f/Work/GitHub/SM/gulpfile.js
/usr/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                   ^
TypeError: Cannot read property 'apply' of undefined
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

В проекте:
```
neks@DESKTOP-ERR8QEQ:/mnt/f/Work/GitHub/SM$ gulp -v
[17:34:41] CLI version 3.9.1
[17:34:41] Local version 4.0.0
```
Глобально:
```
C:\WINDOWS\system32>gulp -v
[17:37:04] CLI version 2.0.1
```
