### ISSUE TITLE
js компиляция

### ISSUE THREAD

**Issue by ABabiy** [agragregra/OptimizedHTML-4#29]
При внесении изменений в файлы js приходится перезапускать вотчер для компиляции  и подгрузки результирующего js.
Можно поправить?

**Comment by rusicsemenov** [comment]
Если консоль не выкидывает ошибок, то проверьте где они находятся, пути за которыми он следит:
'libs/* */*.js', 'app/js/common.js' ну и нежно проверить версия gulp соответствует установленной.
У меня пришлось добавить вместо libs/* */*.js на app/libs/* */*.js

**Comment by ABabiy** [comment]
проверил очень нежно :-) 
Итак, после добавления alert('ttt'); в common.js в самый верх -  алерт не выводится, после перезапуска дефолтного таска - начинает работать как надо. Комментирую, сохраняю - продолжает выводится

**Comment by rusicsemenov** [comment]
Два вопроса:
1. gulp -v
2. путь от gulpfile.js до common.js

**Comment by ABabiy** [comment]
PS C:\OpenServer\domains\ables-agency-1> gulp -v
[21:02:48] CLI version 2.0.1
[21:02:48] Local version 4.0.0
gulpfile.js - стандартно в корне
app/js/common.js - стандартно, без изменений

**Comment by rusicsemenov** [comment]
В консоле я так понимаю тоже нет записи и перепаковке ?  Starting 'scripts'...
Попробуйте для проверки создать папку libs в корне и в ней любой js, перезапустите gulp, будут ли перехвачены изменения. 
Также можно проверить актуальность пакетов через ncu.

ps только что создал новый проект, стартовый шаблон работает без ошибок.

**Comment by ABabiy** [comment]
Вот как это выглядит https://youtu.be/MbYFmB0zNCE

**Comment by wdmcourses** [comment]
Вам не приходила идея, что кэширование может работать на уровне CMS?
Попробуйте отключить кеширование, в OpenCart 3 это делается на главной странице амина справа сверху.

**Comment by ABabiy** [comment]
Это обычная вёрстка обычной страницы без всяких CMS

**Comment by wdmcourses** [comment]
Взглянув на заголовок шторма и на активный значок OpenServer, мне показалось иначе.
В таком случае, трудно сказать, в чём конкретно у вас проблема. Рад бы помочь, да не могу.
