### ISSUE TITLE
Did you forget to signal async completion?

### ISSUE THREAD

**Issue by vimp-dev** [agragregra/OptimizedHTML-4#30]
Алексей, обновил галп с третьего до 4, но из состояния тыквы не вышел. Получаю в консоли при запуске:
`[18:30:35] 'default' errored after 34 ms
[18:30:35] The following tasks did not complete: watch, styles, browser-sync
[18:30:35] Did you forget to signal async completion?`

Я так понял, что где то не указал, что что-то должно быть ассинхронным? Только не пойму где и что.

**Comment by rusicsemenov** [comment]
Вообще то он никому ничего не должен. И с таким обращениям может смело и не реагировать. 
По делу: все пакеты обновили?   ncu проверьте и обновите до последних версий, что с галпом вы обновили до 4? gulp -v что напишет. В крайнем случае проверьте на третьей версии 	gulpversion   = '3'

**Comment by abraus** [comment]
> Я так понял, что где то не указал, что что-то должно быть ассинхронным? Только не пойму где и что.

Вы бы свой код приложили, чтобы посмотреть, быстрее бы ответ получили бы))

**Comment by rusicsemenov** [comment]
Ошибка у него в предпоследней строке:

> gulp.task('default', gulp.parallel('styles', 'scripts', 'browser-sync', 'watch'));

Можно  изменить на 

> gulp.series('default', gulp.parallel('styles', 'scripts', 'browser-sync', 'watch'));

Но для начала нужно быть уверенным в версии галпа вот тут все описано https://fettblog.eu/gulp-4-parallel-and-series/

**Comment by abraus** [comment]
Кстати, вообще не парюсь с глобальным gulp, локальный (в проектах) везде 4
http://take.ms/ogEnJg

**Comment by abraus** [comment]
У меня, конечно, уже далеко не этот сборщик, переделал под свои нужды, но дефолтный таск у меня такой 
http://take.ms/DOKg0O

**Comment by abraus** [comment]
http://take.ms/HaqJ7

**Comment by wdmcourses** [comment]
Есть отдельная виртуальная машина, где разные системы. Там я тестирую на свежем софте всё. И всё работает. Обновите софт и пакеты.

**Comment by vimp-dev** [comment]
> Вообще то он никому ничего не должен. И с таким обращениям может смело и не реагировать.
> По делу: все пакеты обновили? ncu проверьте и обновите до последних версий, что с галпом вы обновили до 4? gulp -v что напишет. В крайнем случае проверьте на третьей версии gulpversion = '3'

Что за манера все в штыки воспринимать? Капец. Вообще то эта возможность гитхаба для обсуждений и создана. Уж извините, что я как вы не родился с безупречными знаниями JS и мне, холопу, приходится сейчас учить и находить ошибки.

**Comment by wdmcourses** [comment]
Не стоит горячиться.

**Comment by vimp-dev** [comment]
> Есть отдельная виртуальная машина, где разные системы. Там я тестирую на свежем софте всё. И всё работает. Обновите софт и пакеты.

Спасибо. Данную ошибку я нашел и исправил, но почему то теперь не отслеживаются html файлы, хотя указаны в вотчере. Буду разбираться
