### ISSUE TITLE
Перехват ошибок обработки js кода

### ISSUE THREAD

**Issue by ABabiy** [agragregra/OptimizedHTML-4#31]
Если была допущена ошибка в JS коде обработка останавливается.
Можно ли сделать по аналогии с sass? Чтобы в консоль выдавалась ошибка но можно было исправить ошибку и результирующий файл компилировался в обычном порядке?

**Comment by rusicsemenov** [comment]
[gulp-jsvalidate](https://www.npmjs.com/package/gulp-jsvalidate) вполне хорошо справляется с данной задачей, только файлы нежно вынести в массив и проверь массивом

> let files = [
>     "app/libs/jquery/dist/jquery.min.js",
>     "app/libs/aos/aos.js",
>     "app/js/common.js", // Always at the end
>   ];
>   return (
>     gulp
>       .src(files)
>       .pipe(jsValidate(files))
>       .pipe(expect(files))
>       .pipe(concat("scripts.min.js"))
>       // .pipe(uglify()) // Mifify js (opt.)
>       .pipe(gulp.dest("app/js"))
>       .pipe(browserSync.reload({ stream: true }))
>   );

**Comment by ABabiy** [comment]
> [gulp-jsvalidate](https://www.npmjs.com/package/gulp-jsvalidate) вполне хорошо справляется с данной задачей, только файлы нежно вынести в массив и проверь массивом

Спасибо! 

И как данный код будет в результате выглядеть? Я наверное не так что-то прописал
gulp.task('scripts', function() {
	return gulp.src([
		'app/libs/jquery/dist/jquery.min.js',
		'app/libs/bootstrap-4.2.1-dist/js/bootstrap.bundle.min.js',
		'app/libs/owl.carousel/dist/owl.carousel.min.js',
		'app/js/common.js', // Always at the end
		])
	.pipe(sourcemaps.init())
	.pipe(concat('scripts.min.js'))
	// .pipe(uglify()) // Mifify js (opt.)
	.pipe(sourcemaps.init())
	.pipe(gulp.dest('app/js'))
	.pipe(browserSync.reload({ stream: true }))
});

**Comment by Demetriusone** [comment]
По-моему правильно будет так 
gulp.task('scripts', function() {
let files = ['app/libs/jquery/dist/jquery.min.js',
'app/libs/bootstrap-4.2.1-dist/js/bootstrap.bundle.min.js',
'app/libs/owl.carousel/dist/owl.carousel.min.js',
'app/js/common.js', // Always at the end
];
return (
gulp.src(files)
.pipe(jsValidate(files))
.pipe(expect(files))
.pipe(sourcemaps.init())
.pipe(concat("scripts.min.js"))
// .pipe(uglify()) // Mifify js (opt.)
.pipe(sourcemaps.init())
.pipe(gulp.dest("app/js"))
.pipe(browserSync.reload({ stream: true }))
});

**Comment by rusicsemenov** [comment]
Да все правильно, но изначально нужно поставить сам валидатор

**Comment by ABabiy** [comment]
Коллеги, огромное спасибо за помощь! :-)
