### ISSUE TITLE
Не следит за изменениями в _*.sass файлах

### ISSUE THREAD

**Issue by Bulkmaker** [agragregra/OptimizedHTML-4#32]
Не обновляется файл main.min.css если сохраняешь _*.sass файлы. Чтобы обновилось, нужно заходить в main.sass и пересохранять его.

В окне терминала он показывает что: 1 file changed (main.min.css) , но по факту в проводнике файл никак не изменился. Только когда изменяешь файл main.sass в свойствах файла main.min.css меняется время изменения и заносятся эти изменения из зависимых файлов.

**Comment by rusicsemenov** [comment]
1. проверьте обновление всех пакетов.
2. в файле gulpfile проверьте syntax
3. Проверьте не изменили ли вы вотчер за стилями первый в заданиях. Должно быть `app/" + syntax + "/**/*." + syntax + "",.... `или `app/" + syntax + "/**/*." + syntax, ....`

**Comment by Bulkmaker** [comment]
> 1. проверьте обновление всех пакетов.
> 2. в файле gulpfile проверьте syntax
> 3. Проверьте не изменили ли вы вотчер за стилями первый в заданиях. Должно быть `app/" + syntax + "/**/*." + syntax + "",.... `или `app/" + syntax + "/**/*." + syntax, ....`

Это всё проверено, на чистом шаблоне тоже самое. main.min.css не меняется пока не обновишь main.sass Причём в браузере стили меняются, а сам файл нет.

**Comment by wdmcourses** [comment]
Ну, это не новость. Открывайте Issue в репозитории Sass.

**Comment by Bulkmaker** [comment]
> Ну, это не новость. Открывайте Issue в репозитории Sass.

Не знал, на 3-ей версии Gulp всё работало.

**Comment by wdmcourses** [comment]
Насколько я знаю, _*.sass файлы, импортируемые в основной всегда имели такую проблему, на всех версиях. Это особенность Sass, ни вотчера, не настроек проекта, ни чего-то ещё.

**Comment by Bulkmaker** [comment]
> Насколько я знаю, _*.sass файлы, импортируемые в основной всегда имели такую проблему, на всех версиях. Это особенность Sass, ни вотчера, не настроек проекта, ни чего-то ещё.

Т. е если импортировать их как обычный файл sass без _ , и gulp.src указать именно main.sass , то всё заработает? нужно попробовать
