### ISSUE TITLE
Пожелание к gulpfile

### ISSUE THREAD

**Issue by XIOLog** [agragregra/OptimizedHTML-4#35]
Добрый день. Подскажите, пожалуйста, как можно использовать gulp-rigger? Есть очень большое желание разбить html-файл на блоки.

**Comment by abraus** [comment]
> Добрый день. Подскажите, пожалуйста, как можно использовать gulp-rigger? Есть очень большое желание разбить html-файл на блоки.

Используйте pug например)

**Comment by XIOLog** [comment]
А сами не планируете реализовать возможность? Многие, я заметил, интересуются :blush:

**Comment by abraus** [comment]
Я использую (со своими изменениями) https://github.com/nicothin/NTH-start-project как вариант. Есть попроще. Поищите.

**Comment by XIOLog** [comment]
Понял. Спасибо большое :-)
