### ISSUE TITLE
Error in plugin "gulp-gm"

### ISSUE THREAD

**Issue by flamedeluxe** [agragregra/OptimizedHTML-4#38]
[14:02:23] Error in plugin "gulp-gm"
Message:
    Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%wx%h" "-" this most likely means the gm/convert binaries can't be found
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false

[14:02:23] 'img' errored after 298 ms
[14:02:23] 'default' errored after 302 ms
[14:02:23] The following tasks did not complete: styles, scripts, browser-sync, watch, img2x
[14:02:23] Did you forget to signal async completion?

**Comment by wdmcourses** [comment]
Серьёзно или это прикол такой? :-D
Я в нескольких местах Gulpfile написал коммент о том, что нужно установить GraphicsMagick, закрепил коммент на YouTube и добавил секцию с руководством по установке на сайте: https://webdesign-master.ru/blog/html-css/2019-05-08-css-gallery.html
Я даже сделал опцию в самом начале Gulpfile для отключения вотчинга картинок, если вам эта возможность не нужна.

**Comment by flamedeluxe** [comment]
Сори) прикол в том что я буквально вчера верстал, все работало, сегодня сколнировал и вдруг ошибка.

**Comment by wdmcourses** [comment]
Установите GM, стартер доработан.

**Comment by flamedeluxe** [comment]
Ок, понял, спасибо за фидбэк

**Comment by wdmcourses** [comment]
Скоро сделаю нормальный Readme.
