### ISSUE TITLE
Why on Ubuntu 19.04 crash npm install?

### ISSUE THREAD

**Issue by opimand** [agragregra/OptimizedHTML-4#39]
Почему сборка не устанавилвается на Ubuntu?
Вот такие вот ошибки вылетают

` gyp verb download contents checksum {"node-v10.15.3-headers.tar.gz":"9e97ee69072836bfbf2a85c4af627ed152574c30c5a32e40fbfcdfda8d9b562e"}
gyp verb validating download checksum for node-v10.15.3-headers.tar.gz (9e97ee69072836bfbf2a85c4af627ed152574c30c5a32e40fbfcdfda8d9b562e == 9e97ee69072836bfbf2a85c4af627ed152574c30c5a32e40fbfcdfda8d9b562e)
gyp verb get node dir target node version installed: 10.15.3
gyp verb build dir attempting to create "build" dir: /home/opimand1/Downloads/OptimizedHTML-4-master/node_modules/node-sass/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/opimand1/Downloads/OptimizedHTML-4-master/node_modules/node-sass/build'
gyp ERR! System Linux 5.0.0-15-generic
gyp ERR! command "/usr/local/bin/node" "/home/opimand1/Downloads/OptimizedHTML-4-master/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/opimand1/Downloads/OptimizedHTML-4-master/node_modules/node-sass
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optimizedhtml@4.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/opimand1/.npm/_logs/2019-05-27T15_34_39_341Z-debug.log
opimand1@undefined:~/Downloads/OptimizedHTML-4-master$ gedit home/opimand1/.npm/_logs/2019-05-27T15_34_39_341Z-debug.log
opimand1@undefined:~/Downloads/OptimizedHTML-4-master$  

`

**Comment by abraus** [comment]
1. <code>rm -rf node_modules package-lock.json</code>
2. <code>npm install</code>

**Comment by opimand** [comment]
> 1. `rm -rf node_modules package-lock.json`
> 2. `npm install`

Это при первой установке, там даже еще нет этой папки и файла

**Comment by abraus** [comment]
`gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/opimand1/Downloads/OptimizedHTML-4-master/node_modules/node-sass/build'`
Права на папки проверяйте. Система пытается создать папку, но доступа нет.

**Comment by opimand** [comment]
> `gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/opimand1/Downloads/OptimizedHTML-4-master/node_modules/node-sass/build'`
> Права на папки проверяйте. Система пытается создать папку, но доступа нет.
все делается через sudo, даже от root пробобвал, та же ошибка

**Comment by opimand** [comment]
> `gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/opimand1/Downloads/OptimizedHTML-4-master/node_modules/node-sass/build'`
> Права на папки проверяйте. Система пытается создать папку, но доступа нет.

Через sudo все деалется, даже через root пробовал, таже ошибка

**Comment by abraus** [comment]
> > `gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/opimand1/Downloads/OptimizedHTML-4-master/node_modules/node-sass/build'`
> > Права на папки проверяйте. Система пытается создать папку, но доступа нет.
> 
> Через sudo все деалется, даже через root пробовал, таже ошибка

А зачем через sudo? Что конкретно вы делаете командой sudo?
поставьте права на папку, если все это дело на локальной машине `sudo chmod 777 /home/optimand/Downloads/OptimizedHTML-4-master/`, 
А вообще обычно создается отдельная папка проектов и вся работа в ней происходит:
`mkdir /home/optimand/dev` - создаем папку
`cd /home/optimand/dev` - переходим в папку проектов
`mkdir project1` - создаем папку нового проекта
`cd project1` - переходим в папку нового проекта 
`git clone git@github.com:agragregra/OptimizedHTML-4.git ./` - клонируем репо в эту папку
`rm -rf .git` - удаляем папку .git
`npm i` - устанавливаем зависимости
Вот и все. все должно работать, если все манипуляции проведены под одним пользователем и не использовалось sudo.
Команды, конечно можно сократить, но расписал, чтобы понятно было

**Comment by abraus** [comment]
Все повторил в виртуалке, смотрите. Все работает http://recordit.co/8XUJbodP0t
