### ISSUE TITLE
UglifyJs ES6

### ISSUE THREAD

**Issue by Lewsha02** [agragregra/OptimizedHTML-4#41]
Если включить минификацию js, то uglifyJs кидает ошибки при использовании ES6, не поддерживается ни новые ключевые слова для объявления переменных (let, const), ни стрелочные функции и т.д прошу исправить, ведь в 2019 пора следовать стандарту ES6, при написании js кода

**Comment by abraus** [comment]
Нормально проходит углификация, что там у вас не так - непонятно. А вообще, у Алексея 5-я версия вышла, [попробуйте её](https://github.com/agragregra/OptimizedHTML-5)

**Comment by maxx52** [comment]
> Нормально проходит углификация, что там у вас не так - непонятно. А вообще, у Алексея 5-я версия вышла, [попробуйте её](https://github.com/agragregra/OptimizedHTML-5)

5-я версия официально еще не вышла, вы сами пробовали ее? У меня она не работает.
А с ES6 проблем нет, все нормально работает, и переменные и стрелочные ф-ции.

**Comment by abraus** [comment]
Мне еще один видосик снять, что все работает? )))

**Comment by abraus** [comment]
> > Нормально проходит углификация, что там у вас не так - непонятно. А вообще, у Алексея 5-я версия вышла, [попробуйте её](https://github.com/agragregra/OptimizedHTML-5)
> 
> 5-я версия официально еще не вышла, вы сами пробовали ее? У меня она не работает.
> А с ES6 проблем нет, все нормально работает, и переменные и стрелочные ф-ции.

покажите вывод консоли, что там пишется

**Comment by maxx52** [comment]
@qfoqs 
module.js:549
    throw err;
    ^
Error: Cannot find module 'gulp-sass'
    at Function.Module._resolveFilename (module.js:547:15)    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/OpenServer/OpenServer/domains/mysite/new/OptimizedHTML-5/gulpfile.js:2:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

Upd: Поставил gulp-sass, теперь так
site/new/OptimizedHTML-5$ gulp
[20:02:40] Using gulpfile /mnt/d/OpenServer/OpenServer/domains/mysite/new/OptimizedHTML-5/gulpfile.js
[20:02:40] Starting 'default'...
[20:02:40] Starting 'img'...
[20:02:40] Starting 'styles'...
[20:02:40] Starting 'scripts'...
[20:02:40] Starting 'browser-sync'...
[20:02:40] Starting 'watch'...
[20:02:40] Starting 'img1x'...
[20:02:40] 'img1x' errored after 457 ms
[20:02:40] Error in plugin "gulp-gm"
Message:
    Error: Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-format" "%wx%h" "-" this most likely means the gm/convert binaries can't be foundDetails:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false

[20:02:40] 'img' errored after 464 ms
[20:02:40] 'default' errored after 467 ms
[20:02:40] The following tasks did not complete: styles, scripts, browser-sync, watch
[20:02:40] Did you forget to signal async completion?

Дальше и не хочу разбираться, ни анонса, ни релиза от автора не было.

**Comment by abraus** [comment]
Вам автор совсем ничего не должен. Данный «сборщик» распространяется бесплатно. если вы внимательно почитаете то, что выдает консоль, а так же третью строку gulpfile.js (комментарий), то, возможно, поймете причину ошибки.
И если вы не хотите разбираться, то попробуйте посмотреть скринкаст И.Кантора по gulp, создайте что-то своё. Вам интересно будет и людям приятно.

**Comment by maxx52** [comment]
> Вам автор совсем ничего не должен. Данный «сборщик» распространяется бесплатно. если вы внимательно почитаете то, что выдает консоль, а так же третью строку gulpfile.js (комментарий), то, возможно, поймете причину ошибки.
> И если вы не хотите разбираться, то попробуйте посмотреть скринкаст И.Кантора по gulp, создайте что-то своё. Вам интересно будет и людям приятно.

Кто сказал, что мне кто-то что-то должен, ты спросил, я ответил. Времени и желания разбираться пока нет.

**Comment by abraus** [comment]
> Кто сказал, что мне кто-то что-то должен, ты спросил, я ответил. Времени и желания разбираться пока нет.

Вы, а не ты. 

И я ничего не спрашивал. Спрашивали вы.

**Comment by maxx52** [comment]
> > Кто сказал, что мне кто-то что-то должен, ты спросил, я ответил. Времени и желания разбираться пока нет.
> 
> Вы, а не ты.

"покажите вывод консоли, что там пишется" - не твои слова. В дальнейшей дискуссии смысла не вижу.

**Comment by wdmcourses** [comment]
OH5
