### ISSUE TITLE
Ошибка с минификацией js

### ISSUE THREAD

**Issue by Lewsha02** [agragregra/OptimizedHTML-4#42]
при объявлении переменной через let или const возникает, вот такая ошибка 
GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected token: keyword «const»

P.S если объявить через var то все работает, но я хочу использовать ES6 стандарт

P.P.S я знаю, что предыдущую проблему закрыли, но мне там, так и не дали ответа, на вопрос, почему не получается использовать ES6

**Comment by wdmcourses** [comment]
https://www.npmjs.com/package/gulp-uglify-es

**Comment by Lewsha02** [comment]
Благодарю
