### ISSUE TITLE
Еще пожелания (Fontawesome)

### ISSUE THREAD

**Issue by alexandershustik** [agragregra/OptimizedHTML-4#43]
Я бы сделал базу вместе с fontawesome.
Чтобы это сделать сейчас:
- качаем шрифт **bower install components-font-awesome --save**
- в файле sass/_libs.sass добавляем
**@import "../libs/components-font-awesome/scss/fontawesome.scss"**
и сам шрифт solid/regular
**@import "../libs/components-font-awesome/scss/solid.scss"**
Все!
Так же я бы поставил jade/pug, но видимо это только моя хотелка, очень мало чуваков юзают этот синтакс

**Comment by devellopah** [comment]
не всем это нужно, просто сделай fork и доработай под свои нужды.
