### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by ra3trub** [agragregra/OptimizedHTML-4#45]
$ gulp
[11:40:10] Using gulpfile /media/DATA/DEV/OptimizedHTML/gulpfile.js
/usr/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:20
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by maxx52** [comment]
Можно попробовать обновить пакеты, ncu, и проверить javascript на ошибки.

**Comment by abraus** [comment]
А лучше выложить свой gulpfile.js

**Comment by ra3trub** [comment]
Я его не изменял просто после распаковки запустил npm i, а затем gulp

**Comment by abraus** [comment]
Ну тогда попробуйте npm cache clean --force
Затем rm -rf node_modules (в папке проекта)
Затем npm i
Затем gulp

**Comment by maxx52** [comment]
Сама сборка работает нормально, я только вчера установил и все без проблем заработало
