### ISSUE TITLE
Не получается запустить OptimizedHTML-4

### ISSUE THREAD

**Issue by ViktorKadkin** [agragregra/OptimizedHTML-4#5]
Здравствуйте Алексей, благодарю за ваш обучающий видео ролик о новом bootstrap. Жду когда выйдет видео ролик о OptimizedHTML-4, но уже возникла необходимость сделать фронт-энд проект, хотел воспользоваться вашим стартовым шаблоном, однако при установке получил кучу ошибок (прилагаю скриншоты). Пробовал переустановить gulp и node js, ничего не помогло. После команды gulp в терминале шаблон запускается, но поля ip адресов пустые, livereload не работает. Может быть вы сталкивались с такими же проблемами, и добавите информацию по их решение в новый ролик!
![error_log](https://user-images.githubusercontent.com/20230209/36349124-242a8a56-14aa-11e8-87ea-0fd86ad4e1a4.JPG)
![bower](https://user-images.githubusercontent.com/20230209/36349129-2c5ef414-14aa-11e8-8df9-18aa312c63dc.JPG)

**Comment by htmldesigner** [comment]
Здравствуйте Алексей! Такая же проблема как у чувака сверху.

**Comment by wdmcourses** [comment]
Используйте подсистему Linux.

**Comment by evgeniy-vashchuk** [comment]
По скриншотам вроде как у Вас всё правильно установилось...

Поля не пустые, а прозрачные (попробуйте выделить и скопировать - обновлённий PowerShell почему-то делает розовый цвет - прозрачным. Решения в интернете не нашёл - перешёл на ConEmu

**Comment by rusicsemenov** [comment]
Специально , скачал проверить новую версию, все работает. При установке накатываются 837 пакетов, у вас 705. 

До этого пробовал ставить opt+sass+ject были ошибки, решились установкой глобально библиотек  npm install -g windows-build-tools теперь все работает как часы везде. Проверьте.

**Comment by ViktorKadkin** [comment]
Благодарю всех, кто попытался мне помочь, особая благодарность Алексею, его совет мне помог. Всем рекомендую использовать Git Bash терминал, вместо PowerShell.
