### ISSUE TITLE
Сместились media-breakpoint-down

### ISSUE THREAD

**Issue by joidru** [agragregra/OptimizedHTML-4#50]
Здравствуйте, видимо после последнего обновления сместились media-breakpoint-down, тоесть:
 
+media-breakpoint-down(xs) - если установить под ним какие то значения то они переопределят то что есть в main.sass
+media-breakpoint-down(sm) - тут XS
+media-breakpoint-down(md) - тут SM
+media-breakpoint-down(lg) - тут MD
+media-breakpoint-down(xl) - тут LG

Как можно это исправить?

+media-breakpoint-up - вроде как работают правильно

**Comment by wdmcourses** [comment]
Просто всё, что раньше писали в xs - размещаете в sm.

**Comment by joidru** [comment]
Логично) Спасибо
