### ISSUE TITLE
Error: Could not execute GraphicsMagick/ImageMagick

### ISSUE THREAD

**Issue by joidru** [agragregra/OptimizedHTML-4#52]
Привет, что то стартовый шаблон перестал запускаться, выдает такую ошибку:

Message:
    Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%wx%h" "-" this most likely means the gm/convert binaries can't be found
Details:
    domainEmitter: [object Object]
    domainThrown: false

старые версии работают

**Comment by wdmcourses** [comment]
Fixed
Line 3
