### ISSUE TITLE
Предупреждения в консоли, после ввода команды npm install

### ISSUE THREAD

**Issue by banha-serhii** [agragregra/OptimizedHTML-4#8]
После ввода команды `npm install  ` отображаются предупреждения в консоли
![image](https://user-images.githubusercontent.com/16404807/37084980-9db79062-21fc-11e8-8df3-97d481d58e01.png)

**Comment by rusicsemenov** [comment]
Ну так написано устаревшие компоненты,  проверьте возможно установлены глобально. npm ls minimatch или npm ls gulp-util итп а глобально добавить нужно -g. И после этого обновить их  npm install minimatch@3.0.2 --save-dev .  Также было вроде сказано использовать ncu -u должно вроде решать эти задачи. Может меня поправят.

**Comment by banha-serhii** [comment]
Да, вы правы, можно закрывать тикет, так как я сначала скачал исходники и работал с ними, а уже потом смотрел видео
